
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    hello:
      itemservice:
        repository:
          mybatis: trace
spring:
  profiles:
    active: local
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
